data:extend({
  {
    type = "item-subgroup",
    name = "data-fluid",
    group = "fluids",
    order = "b[data]"
  },
  {
    type = "fluid",
    name = "raw-data",
    subgroup = "data-fluid",
    order = "a[raw-data]",
    default_temperature = 15,
    base_color = {26, 117, 64},
    flow_color = {26, 117, 64},
    icon = "__Moshine__/graphics/icons/raw-data.png",
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "cosmic-data-outsignal",
    subgroup = "data-fluid",
    order = "b[cosmic-data-outsignal]",
    default_temperature = 15,
    base_color = {30, 30, 170},
    flow_color = {30, 30, 170},
    icon = "__Moshine__/graphics/icons/cosmic-data-outsignal.png",
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "cosmic-data",
    subgroup = "data-fluid",
    order = "c[cosmic-data]",
    default_temperature = 15,
    base_color = {5, 5, 15},
    flow_color = {5, 5, 15},
    icon = "__Moshine__/graphics/icons/cosmic-data.png",
    auto_barrel = false,
  },
})