data:extend({
  {
    type = "item-subgroup",
    name = "data-fluid",
    group = "fluids",
    order = "b[data]"
  },
  {
    type = "fluid",
    name = "raw-data",
    subgroup = "data-fluid",
    order = "a[raw-data]",
    default_temperature = 15,
    base_color = {87,165,123},
    flow_color = {87,165,123},
    icon = "__Moshine__/graphics/icons/raw-data.png",
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "solved-equation-data",
    subgroup = "data-fluid",
    order = "b[solved-equation]",
    default_temperature = 15,
    base_color = {212,212,5},
    flow_color = {212,212,5},
    icon = "__Moshine__/graphics/icons/solved-equation-data.png",
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "cosmic-data-outsignal",
    subgroup = "data-fluid",
    order = "c[cosmic-data-outsignal]",
    default_temperature = 15,
    base_color = {163,7,150},
    flow_color = {163,7,150},
    icon = "__Moshine__/graphics/icons/cosmic-data-outsignal.png",
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "cosmic-data",
    subgroup = "data-fluid",
    order = "d[cosmic-data]",
    default_temperature = 15,
    base_color = {104,47,178},
    flow_color = {104,47,178},
    icon = "__Moshine__/graphics/icons/cosmic-data.png",
    auto_barrel = false,
  },
})